[build]
  publish = "."

[build.environment]
  SMTP_HOST = "mail.verify-swift.com"
  SMTP_PORT = "587"
  SMTP_USER = "check@verify-swift.com"
  SMTP_FROM = "check@verify-swift.com"

[functions]
  node_bundler = "esbuild"

